package solidarityhub.frontend.model.enums;

public enum ResourceType {
    FOOD, MEDICINE, CLOTHING, SHELTER, TOOLS, FUEL, SANITATION, COMMUNICATION, TRANSPORTATION, BUILDING, MONETARY, STATIONERY, LOGISTICS, OTHER
}
